### ISSUE TITLE
0.8版本CRUD生成代码token数受限无法提交模型处理

### ISSUE THREAD

**Issue by shenxunan** [unit-mesh/auto-dev#14]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/077b96c7-dbed-42cd-a611-239973c0030d)

**Comment by phodal** [comment]
有空可以来 PR

**Comment by shenxunan** [comment]
> 有空可以来 PR

OK

**Comment by yanghuijava** [comment]
我在1.0版本中遇到是限速问题：
com.theokanning.openai.OpenAiHttpException: Rate limit reached for default-gpt-3.5-turbo in organization org-jg9aweCxRNo99k8Ah6g3srjm on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
	at com.theokanning.openai.service.ResponseBodyCallback.onResponse(ResponseBodyCallback.java:53)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: retrofit2.HttpException: HTTP 429 
	at com.theokanning.openai.service.ResponseBodyCallback.onResponse(ResponseBodyCallback.java:43)
	... 5 more

**Comment by GeekyWizKid** [comment]
> ![image](https://user-images.githubusercontent.com/131851109/258022503-077b96c7-dbed-42cd-a611-239973c0030d.png)

可以使用 16k 模型 
<img width="698" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/133981481/e12aee9a-b624-43b9-b1f5-6eaabbff2ade">
