### ISSUE TITLE
test gen error: can't create test file

### ISSUE THREAD

**Issue by iptton** [unit-mesh/auto-dev#152]
when generating test for file in a submodule of gradle project , error occurred:

```
java.lang.Throwable: Source file is not in the src/main/java directory: /{my computer}/MyProject/SubModule/src/main/java/pack/age/to/file
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at cc.unitmesh.kotlin.provider.KotlinAutoTestService.findOrCreateTestFile(KotlinAutoTestService.kt:57)
	at cc.unitmesh.devti.intentions.action.task.TestCodeGenTask.run(TestCodeGenTask.kt:61)
```

```
his progress indicator (测试此代码 1247087534: running=true; canceled=false; task=cc.unitmesh.devti.intentions.action.task.TestCodeGenTask@2efacf7a) is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress. class com.intellij.openapi.progress.impl.BackgroundableProcessIndicator
java.lang.IllegalStateException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.setFraction(AbstractProgressIndicatorBase.java:211)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.setFraction(AbstractProgressIndicatorExBase.java:119)
	at com.intellij.openapi.progress.util.ProgressWindow.setFraction(ProgressWindow.java:333)
	at cc.unitmesh.devti.intentions.action.task.TestCodeGenTask.run(TestCodeGenTask.kt:57)
```

```
java.lang.Throwable: Failed to create test file for: KtFile: MyFileName.kt
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at cc.unitmesh.devti.intentions.action.task.TestCodeGenTask.run(TestCodeGenTask.kt:72)
```

**Comment by phodal** [comment]
目前好像是 setIndeterminate  的问题？

**Comment by iptton** [comment]
> 目前好像是 setIndeterminate 的问题？
> 
> 上一个版本好像已经修了：[5f139d9#diff-39ca5a13ebc19bf3e4bf11e9d76cba80ff2bba9e5cdc944a3150f5e46ea3ac38L46](https://github.com/unit-mesh/auto-dev/commit/5f139d94bb16ce62fc283499e7e374457b3c7f74#diff-39ca5a13ebc19bf3e4bf11e9d76cba80ff2bba9e5cdc944a3150f5e46ea3ac38L46)

我本地是 1.8.0-241 ，setIndeterminate 只是个 Info ，不是错误。
bug 表现是测试文件不会被创建出来

**Comment by iptton** [comment]
Source file is not in the src/main/java directory: /{my computer}/MyProject/SubModule/src/main/java/pack/age/to/file

这外错误有点问题吧？打出来的日志明显路径里就有 src/main/java 呀

**Comment by phodal** [comment]
有两个问题

1.  `KotlinAutoTestService.kt:57` 写的是 `src/main/java` 应该改为 `src/main/kotlin`
2. Java  的测试不应该触发到  Kotlin  的测试生成才对。

**Comment by phodal** [comment]
嗯，理论上正确的方式应该是去  Gradle  的  sourceset  拿，所以在  IDE  中会有一个 popup window 来让用户选择。
