### ISSUE TITLE
1.0版本运行devti://story/github/1报错

### ISSUE THREAD

**Issue by shenxunan** [unit-mesh/auto-dev#19]
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at cc.unitmesh.idea.spring.JavaSpringCodeCreator.createControllerOrUpdateMethod(JavaSpringCodeCreator.kt:282)
	at cc.unitmesh.idea.flow.provider.JvmAutoDevFlow.createCode(JvmAutoDevFlow.kt:220)
	at cc.unitmesh.idea.flow.provider.JvmAutoDevFlow.createCodeByType(JvmAutoDevFlow.kt:208)
	at cc.unitmesh.idea.flow.provider.JvmAutoDevFlow.createCodeByType$default(JvmAutoDevFlow.kt:202)
	at cc.unitmesh.idea.flow.provider.JvmAutoDevFlow.createServiceFile(JvmAutoDevFlow.kt:186)
	at cc.unitmesh.idea.flow.provider.JvmAutoDevFlow.updateOrCreateServiceAndRepository(JvmAutoDevFlow.kt:141)
	at cc.unitmesh.devti.runconfig.AutoDevRunProfileState$executeCrud$1.run(AutoDevRunProfileState.kt:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by phodal** [comment]
OpenAI 有时返回的结果没有 mush 格式

**Comment by shenxunan** [comment]
是每次都这样哈， 还有一个问题是多执行几次，又报token超长了。

**Comment by phodal** [comment]
我有空看一下，token 超长在 #14 里有。

**Comment by shenxunan** [comment]
> 

什么原因造成的？ 有修复方案不？

**Comment by phodal** [comment]
原因看代码嘛

**Comment by shenxunan** [comment]
> 原因看代码嘛
我理解这个是上下文信息拼接太长了，应该想办法控制一下token长度，跟设计方案有关

**Comment by phodal** [comment]
控制 token 长度也算是个方案，但是直接用16k 的不是更简单？

**Comment by phodal** [comment]
应该把 token 变成可配置的

<img width="866" alt="image" src="https://github.com/unit-mesh/auto-dev/assets/472311/bb0fd901-be19-4219-8e37-9aeb022ac923">
