### ISSUE TITLE
request rate limit

### ISSUE THREAD

**Issue by hotip** [unit-mesh/auto-dev#21]
consider provide setting to limit request rate

```
com.theokanning.openai.OpenAiHttpException: Rate limit reached for default-gpt-3.5-turbo in organization org-lpTV8JA1Fonfq3PljHSxtabv on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
	at com.theokanning.openai.service.ResponseBodyCallback.onResponse(ResponseBodyCallback.java:53)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by phodal** [comment]
欢迎来 Pull request

**Comment by GeekyWizKid** [comment]
这个问题似乎没什么好办法，免费api调用频率过高就会被拒绝

**Comment by GeekyWizKid** [comment]
这个问题似乎没什么好办法，免费api调用频率过高就会被拒绝
