### ISSUE TITLE
onCompletion You LLM server Key is empty,custom llm server key已经设置并保存

### ISSUE THREAD

**Issue by belingud** [unit-mesh/auto-dev#221]
**Describe the bug**
使用custom llm配置，test llm connection 正常，但是chat无法使用

**To Reproduce**
1. 右侧AutoDev
2. 发送hi

**Expected behavior**
chat正常响应和使用

**Screenshots**
<img width="908" alt="image" src="https://github.com/user-attachments/assets/520376cd-6e82-45e8-84ff-f0cafbaf86c2">

<img width="1424" alt="image" src="https://github.com/user-attachments/assets/a9c5c5a8-06ea-4875-a6ba-eddb72ab5456">

**Desktop:**
 - OS: Mac Sonoma
 - Main 1.8
 - IDEA Version Intellij IDEA 2024.1

**Additional context**
错误日志

```shell
2024-08-05 16:26:41,512 [76368176]   INFO - #cc.unitmesh.devti.llms.openai.OpenAIProvider - messages length: 2
2024-08-05 16:26:41,514 [76368178]   INFO - #cc.unitmesh.devti.gui.chat.ChatCodingPanel - onCompletion You LLM server Key is empty
2024-08-05 16:26:41,515 [76368179]   INFO - STDERR - java.lang.IllegalStateException: You LLM server Key is empty
2024-08-05 16:26:41,515 [76368179]   INFO - STDERR - 	at cc.unitmesh.devti.llms.openai.OpenAIProvider.getService(OpenAIProvider.kt:56)
2024-08-05 16:26:41,515 [76368179]   INFO - STDERR - 	at cc.unitmesh.devti.llms.openai.OpenAIProvider.access$getService(OpenAIProvider.kt:33)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at cc.unitmesh.devti.llms.openai.OpenAIProvider$stream$1$1.invokeSuspend(OpenAIProvider.kt:122)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-08-05 16:26:41,516 [76368180]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by phodal** [comment]
对非  SSE  支持不好，建议不要用  JSON
