### ISSUE TITLE
java.lang.Throwable: Read access is allowed from inside read-action (or EDT)

### ISSUE THREAD

**Issue by xifengzhu** [unit-mesh/auto-dev#3]
IDEA版本： IntelliJ IDEA 2023.1 (Ultimate Edition) Build #IU-231.8109.175, built on March 28, 2023

配置好之后报错如下:
```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[ApplicationImpl pooled thread 43,4,main] 21718972 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 854203447
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:184)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:621)
	at com.intellij.psi.impl.source.PsiFileImpl.getGreenStubTree(PsiFileImpl.java:956)
	at com.intellij.psi.impl.source.SpineRef.getGreenStub(SpineRef.java:36)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getGreenStub(StubBasedPsiElementBase.java:352)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getParent(StubBasedPsiElementBase.java:314)
	at cc.unitmesh.devti.actions.CodeCompleteAction$actionPerformed$task$1.run(CodeCompleteAction.kt:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by LSXCH** [comment]
Same issue.

**Comment by phodal** [comment]
是没有调用 runWriteCommandAction 或者 runReadCommandAction 导致的。 最近比较忙，有时间我再看一下。

**Comment by gchen2015** [comment]
这个问题7月1日尝试的时候还在，目前解决了吗，谢谢

**Comment by phodal** [comment]
最近比较忙，没啥精力修🥹🥹🥹

**Comment by gchen2015** [comment]
打扰一下，您之前运行成功的IDEA版本是什么呀？

**Comment by phodal** [comment]
理论上每个版本都可以成功运行，只是有的 throwable 一定会出现

**Comment by phodal** [comment]
能详细说一下使用的过程吗？

**Comment by gchen2015** [comment]
1 我手工安装了插件 在devti 设置了模型是用的GPT3.5
2 我写如下的类
   @RestController
public class BlogController {

    // devti://story/github/1
}
3 运行autocurd插件，第1,2 步都运行成功的，github issue story也正确的拆分了故事，第3步的时候 感觉代码也快生产了
但是产生了如上的错误，我切换了不同Idea版本都是这个错，分别是版本 IntelliJ IDEA Community Edition 2022.3.1 和 IntelliJ IDEA Community Edition 2023.1.3

**Comment by phodal** [comment]
别的功能应该 OK，你们是想探索这个场景下的自动编码？
