### ISSUE TITLE
代码回写时报错

### ISSUE THREAD

**Issue by GeekyWizKid** [unit-mesh/auto-dev#40]
报错信息如下：
```log
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
...
...
```

**Comment by phodal** [comment]
回写是指？有没有更详细的异常调用链

**Comment by GeekyWizKid** [comment]
Run Devti 生成代码后无法创建代码文件
详细错误信息如下：
```log
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 6,4,main] 1378972300
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 843680914
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1110)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1093)
	at com.intellij.openapi.editor.impl.view.EditorView.assertIsDispatchThread(EditorView.java:704)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:284)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1965)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:253)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1122)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:235)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent.paintForceDoubleBuffered(JComponent.java:1158)
	at java.desktop/javax.swing.JViewport.blitDoubleBuffered(JViewport.java:1731)
	at java.desktop/javax.swing.JViewport.windowBlitPaint(JViewport.java:1684)
	at java.desktop/javax.swing.JViewport.setViewPosition(JViewport.java:1219)
	at com.intellij.ui.components.JBViewport.setViewPosition(JBViewport.java:105)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.vsbStateChanged(BasicScrollPaneUI.java:1189)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(BasicScrollPaneUI.java:1178)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:371)
	at com.intellij.ui.components.JBScrollBar$Model.fireStateChanged(JBScrollBar.java:364)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:309)
	at java.desktop/javax.swing.DefaultBoundedRangeModel.setValue(DefaultBoundedRangeModel.java:175)
	at java.desktop/javax.swing.JScrollBar.setValue(JScrollBar.java:486)
	at com.intellij.ui.components.JBScrollBar.setValue(JBScrollBar.java:196)
	at cc.unitmesh.devti.gui.chat.ChatCodingPanel.scrollToBottom(ChatCodingPanel.kt:166)
	at cc.unitmesh.devti.gui.chat.ChatCodingPanel.addMessage(ChatCodingPanel.kt:134)
	at cc.unitmesh.idea.flow.JvmAutoDevFlow.executePrompt(JvmAutoDevFlow.kt:287)
	at cc.unitmesh.idea.flow.JvmAutoDevFlow.fetchSuggestEndpoint(JvmAutoDevFlow.kt:97)
	at cc.unitmesh.devti.runconfig.AutoDevRunProfileState$executeCrud$1.run(AutoDevRunProfileState.kt:89)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
IDEA version: IntelliJ IDEA 2022.2.4 (Ultimate Edition)

**Comment by GeekyWizKid** [comment]
这是 sof 上关于此bug 的描述
https://stackoverflow.com/questions/54826606/intellij-plugin-access-is-allowed-from-event-dispatch-thread-only

**Comment by phodal** [comment]
看上去是 scroll 的时候出错？

```bash
at cc.unitmesh.devti.gui.chat.ChatCodingPanel.scrollToBottom(ChatCodingPanel.kt:166)
	at cc.unitmesh.devti.gui.chat.ChatCodingPanel.addMessage(ChatCodingPanel.kt:134)
	at cc.unitmesh.idea.flow.JvmAutoDevFlow.executePrompt(JvmAutoDevFlow.kt:287)
	at cc.unitmesh.idea.flow.JvmAutoDevFlow.fetchSuggestEndpoint(JvmAutoDevFlow.kt:97)
	at cc.unitmesh.devti.runconfig.AutoDevRunProfileState$executeCrud$1.run(AutoDevRunProfileState.kt:89)
```

**Comment by GeekyWizKid** [comment]
是的，回头我提个pr上来
