### ISSUE TITLE
升级1.2.2版本之后插件报错，1.2.1版本正常

### ISSUE THREAD

**Issue by chisifang** [unit-mesh/auto-dev#47]
idea版本：IntelliJ IDEA 2023.2.2 (Ultimate Edition)  Build #IU-232.9921.47, built on September 13, 2023
使用场景：配置了custom engine server
问题版本：1.2.2，报错内容如下：
  Unhandled exception in [StandaloneCoroutine{Cancelling}@183c00b, Dispatchers.Default]
  
  java.lang.NumberFormatException: For input string: ""
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Long.parseLong(Long.java:721)
at java.base/java.lang.Long.parseLong(Long.java:836)
at cc.unitmesh.devti.gui.chat.ChatCodingPanel$updateMessageInUi$3.invokeSuspend(ChatCodingPanel.kt:217)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@183c00b, Dispatchers.Default]

备注：1.2.1版本没有报错，模型返回解析正常

**Comment by phodal** [comment]
啊这，有没有更详细的错误信息？可以从这里下载旧版本：https://plugins.jetbrains.com/plugin/21520-autodev/versions

**Comment by phodal** [comment]
或者能不能看看配置文件是不是正常的，比如我的

配置文件路径： ~/Library/Application\ Support/JetBrains/IntelliJIdea2023.2/options/DevtiSettings.xml

内容

```
<application>
  <component name="cc.unitmesh.devti.settings.DevtiSettingsState">
    <option name="customOpenAiHost" value="https://api.aios.chat/" />
    <option name="openAiKey" value="xxx" />
    <option name="openAiModel" value="gpt-3.5-turbo" />
  </component>
</application>
```

**Comment by chisifang** [comment]
效率太高！

**Comment by phodal** [comment]
更新了新版本，但是需要等 JetBrains 审核，如果等不及的话，可以从这里下载：https://github.com/unit-mesh/auto-dev/releases/tag/v1.2.3

**Comment by phodal** [comment]
JetBrains 的应用商店已经更新好了，可以试试：https://plugins.jetbrains.com/plugin/21520-autodev

**Comment by chisifang** [comment]
@phodal 升级1.2.3不报错，但是模型返回的数据流没有正常输出。回滚到1.2.1版本之后一切正常

**Comment by hotip** [comment]
> @phodal 升级1.2.3不报错，但是模型返回的数据流没有正常输出。回滚到1.2.1版本之后一切正常。 模型服务一直没有改过，输入输出都是按照文档要求。 从现象看，就是1.2.1之后的版本对返回数据解析做了调整

发一下输入输出我看下？

**Comment by hotip** [comment]
> @phodal 升级1.2.3不报错，但是模型返回的数据流没有正常输出。回滚到1.2.1版本之后一切正常。 模型服务一直没有改过，输入输出都是按照文档要求。 从现象看，就是1.2.1之后的版本对返回数据解析做了调整

建议新起个 issue
