### ISSUE TITLE
what reason?

### ISSUE THREAD

**Issue by shenxunan** [unit-mesh/auto-dev#6]
java.lang.RuntimeException: java.net.SocketTimeoutException: Connect timed out
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:90)
	at io.reactivex.Single.blockingGet(Single.java:2002)
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:260)
	at com.theokanning.openai.service.OpenAiService.createChatCompletion(OpenAiService.java:129)
	at cc.unitmesh.devti.connector.openai.OpenAIConnector.prompt(OpenAIConnector.kt:84)
	at cc.unitmesh.devti.gui.chat.ChatCodingService.makeChatBotRequest(ChatCodingService.kt:54)
	at cc.unitmesh.devti.gui.chat.ChatCodingService.handlePromptAndResponse$lambda$1(ChatCodingService.kt:33)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at com.theokanning.openai.service.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2517)
	at io.reactivex.Single.blockingGet(Single.java:2001)
	... 15 more

**Comment by phodal** [comment]
Connect timed out... Check you network connection to OpenAI server.

**Comment by shenxunan** [comment]
需要在idea里设置连接地址吗？ 我设置了全局梯子，连github copilot、chatgpt都没问题的。

**Comment by phodal** [comment]
不确定，可以在 IDEA 里测试 connection 试试

**Comment by shenxunan** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/e16c91ab-52da-4bc8-8160-a1a2ae39d5e7)

**Comment by shenxunan** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/80d178f0-9b77-4a95-a7e1-eb85738da6d4)

**Comment by phodal** [comment]
<img width="1006" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/9a66bb26-45a9-4bb8-bd02-296dac5871d5">

**Comment by shenxunan** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/6a58cd0f-56bc-42cc-b157-23a055157da2)

**Comment by shenxunan** [comment]
貌似需要设置用户、密码

**Comment by shenxunan** [comment]
![image](https://github.com/unit-mesh/auto-dev/assets/131851109/dbe238f1-8059-4a19-8a98-9c6ef65f5f48)

**Comment by shenxunan** [comment]
这个用户名和密码是什么呢？

**Comment by phodal** [comment]
不需要啊，你在 IDEA 测试能不能连上，如果 401 就证明可以

**Comment by shenxunan** [comment]
OK了，感谢！
