### ISSUE TITLE
Custom模式下，自定义Custom Engine Prompt 报错

### ISSUE THREAD

**Issue by songyb-jk** [unit-mesh/auto-dev#71]
```
2024-01-08 14:48:59,875 [ 107915]   INFO - #c.u.d.c.a.CustomPromptConfig - Loaded prompt config: CustomPromptConfig(spec={}, prompts=[cc.unitmesh.devti.custom.action.CustomIntentionConfig@630ee774], documentations=null)
2024-01-08 14:48:59,935 [ 107975]   INFO - #c.u.d.c.a.CustomPromptConfig - Loaded prompt config: CustomPromptConfig(spec={}, `prompts=[cc.unitmesh.devti.custom.action.CustomIntentionConfig@21012da9],` documentations=null)
2024-01-08 14:49:02,070 [ 110110]   INFO - #c.u.d.c.a.CustomPromptConfig - Loaded prompt config: CustomPromptConfig(spec={}, prompts=[cc.unitmesh.devti.custom.action.CustomIntentionConfig@58a77216], documentations=null)
2024-01-08 14:49:03,051 [ 111091]   INFO - #c.u.d.c.a.CustomPromptConfig - Loaded prompt config: CustomPromptConfig(spec={}, prompts=[cc.unitmesh.devti.custom.action.CustomIntentionConfig@2e2d671b], documentations=null)
2024-01-08 14:49:03,082 [ 111122]   INFO - STDERR - SLF4J: No SLF4J providers were found.
2024-01-08 14:49:03,084 [ 111124]   INFO - STDERR - SLF4J: Defaulting to no-operation (NOP) logger implementation
2024-01-08 14:49:03,084 [ 111124]   INFO - STDERR - SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
2024-01-08 14:49:03,084 [ 111124]   INFO - STDERR - SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
2024-01-08 14:49:03,085 [ 111125]   INFO - STDERR - SLF4J: Ignoring binding found at [jar:file:/C:/software/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202022.2.5/lib/3rd-party-rt.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2024-01-08 14:49:03,086 [ 111126]   INFO - STDERR - SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
2024-01-08 14:49:03,136 [ 111176] SEVERE - #c.i.i.p.PluginManager - Velocity could not be initialized!
java.lang.RuntimeException: Velocity could not be initialized!
        at org.apache.velocity.runtime.RuntimeInstance.requireInitialization(RuntimeInstance.java:376)
        at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:1323)
        at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1433)
        at org.apache.velocity.runtime.RuntimeInstance.evaluate(RuntimeInstance.java:1395)
        at org.apache.velocity.app.Velocity.evaluate(Velocity.java:184)
        at cc.unitmesh.devti.custom.CustomActionIntention.buildCustomPrompt(CustomActionIntention.kt:85)
        at cc.unitmesh.devti.custom.CustomActionIntention.invoke(CustomActionIntention.kt:46)
        at cc.unitmesh.devti.intentions.IntentionsActionGroup$getChildren$1$1.invoke(IntentionsActionGroup.kt:25)
        at cc.unitmesh.devti.intentions.IntentionsActionGroup$getChildren$1$1.invoke(IntentionsActionGroup.kt:24)
        at cc.unitmesh.devti.intentions.IntentionsActionGroup.getChildren$lambda$1$lambda$0(IntentionsActionGroup.kt:24)
        at com.intellij.openapi.project.DumbAwareAction$SimpleDumbAwareAction.actionPerformed(DumbAwareAction.java:82)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:294)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:294)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$4(ActionMenuItem.java:293)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:286)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:67)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:109)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:546)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:578)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6656)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
        at java.desktop/java.awt.Component.processEvent(Component.java:6421)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2804)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:790)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:763)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:761)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:760)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: org.apache.velocity.exception.VelocityException: The specified class for ResourceManager (org.apache.velocity.runtime.resource.ResourceManagerImpl) does not implement org.apache.velocity.runtime.resource.ResourceManager; Velocity is not initialized correctly.
at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:824)
        at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:282)
        at org.apache.velocity.runtime.RuntimeInstance.requireInitialization(RuntimeInstance.java:371)
        ... 66 more
2024-01-08 14:49:03,141 [ 111181] SEVERE - #c.i.i.p.PluginManager - IntelliJ IDEA 2022.2.5  Build #IC-222.4554.10
2024-01-08 14:49:03,142 [ 111182] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-01-08 14:49:03,143 [ 111183] SEVERE - #c.i.i.p.PluginManager - OS: Windows 7
2024-01-08 14:49:03,144 [ 111184] SEVERE - #c.i.i.p.PluginManager - Plugin to blame: AutoDev version: 1.5.2-222
2024-01-08 14:49:04,223 [ 112263]   INFO - #o.k.p.KafkaStateComponent - Save state:{}{}
2024-01-08 14:49:04,278 [ 112318]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 15 ms, FindSettings took 13 ms, KeymapManager took 11 ms, KotlinRejectersInfoService took 18 ms
2024-01-08 14:49:05,919 [ 113959]   INFO - #c.u.d.c.a.CustomPromptConfig - Loaded prompt config: CustomPromptConfig(spec={}, prompts=[cc.unitmesh.devti.custom.action.CustomIntentionConfig@212d58b7], documentations=null)
2024-01-08 14:49:06,081 [ 114121]   INFO - #c.i.o.a.i.PopupMenuPreloader - 7134 ms since showing to preload popup menu 'Editor Popup Menu' at 'EditorPopup' in 163 ms

```

**Comment by phodal** [comment]
不能复现，会不会是模板写得有问题。

**Comment by songyb-jk** [comment]
模版如下
`{
	"prompts": [
	    {
	      "title": "代码优化",
	      "autoInvoke": false,
	      "matchRegex": ".*",
	      "priority": 1000,
	      "template": "对下面这段Java代码进行优化\n${SELECTION}"
	    }
  ]
}`

**Comment by phodal** [comment]
我这没有复现，估计是偶发的 bug，

<img width="1297" alt="图片" src="https://github.com/unit-mesh/auto-dev/assets/472311/8ed14d23-2e44-4d62-985c-e6a34a3a2989">

**Comment by songyb-jk** [comment]
```
2024-01-08 14:49:03,142 [ 111182] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-01-08 14:49:03,143 [ 111183] SEVERE - #c.i.i.p.PluginManager - OS: Windows 7
```
跟JDK版本有没有关系，我这边是毕现的

**Comment by phodal** [comment]
可能性不大，通常 JDK  是固定的

```
2024-01-08 15:38:25,746 [18179582] SEVERE - #c.i.o.e.i.EditorFactoryImpl - IntelliJ IDEA 2023.3.2  Build #IU-233.13135.103
2024-01-08 15:38:25,746 [18179582] SEVERE - #c.i.o.e.i.EditorFactoryImpl - JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-01-08 15:38:25,746 [18179582] SEVERE - #c.i.o.e.i.EditorFactoryImpl - OS: Mac OS X
2024-01-08 15:38:25,747 [18179583] SEVERE - #c.i.o.e.i.EditorFactoryImpl - Plugin to blame: Mermaid version: 0.0.18+IJ.232
```

**Comment by phodal** [comment]
理论上可以尝试，https://stackoverflow.com/questions/1586133/apache-velocity-can-not-initialize

**Comment by songyb-jk** [comment]
好的，我再试试，感谢黄老师

**Comment by phodal** [comment]
估计需要你本地  debug  一下了
