### ISSUE TITLE
json解析异常

### ISSUE THREAD

**Issue by HMcode-tech** [unit-mesh/auto-dev#72]
填的参数
Custom Request Body Format(Json File): 
{"customFields":{"model":"/data/model/deepseek-coder-33b-instruct","stop":["<|im_end>|","|EOT|"],"stream":0}} 

完整异常
Failed to parse custom request body

java.lang.IllegalArgumentException: Element class kotlinx.serialization.json.JsonArray is not a JsonPrimitive
	at kotlinx.serialization.json.JsonElementKt.error(JsonElement.kt:326)
	at kotlinx.serialization.json.JsonElementKt.getJsonPrimitive(JsonElement.kt:229)
	at cc.unitmesh.devti.llms.custom.CustomLLMProviderKt.updateCustomBody(CustomLLMProvider.kt:216)
	at cc.unitmesh.devti.llms.custom.CustomLLMProviderKt.updateCustomFormat(CustomLLMProvider.kt:252)
	at cc.unitmesh.devti.llms.custom.CustomLLMProvider.stream(CustomLLMProvider.kt:82)
	at cc.unitmesh.devti.gui.chat.ChatCodingService.makeChatBotRequest(ChatCodingService.kt:84)
	at cc.unitmesh.devti.gui.chat.ChatCodingService.handlePromptAndResponse$lambda$1(ChatCodingService.kt:47)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by phodal** [comment]
现在的代码实现里应该不支持  Array  的方式，欢迎来  PR。

https://github.com/unit-mesh/auto-dev/blob/e25e91e195ec9f99927fb8f47fb9edf93e112c34/src/main/kotlin/cc/unitmesh/devti/llms/custom/CustomLLMProvider.kt#L214-L218

**Comment by HMcode-tech** [comment]
谢谢黄老师，已经调通了
