### ISSUE TITLE
 the generate document function get error !

### ISSUE THREAD

**Issue by lixikun** [unit-mesh/auto-dev#99]
when I use the generate document function, I get the follwing error.
![image](https://github.com/unit-mesh/auto-dev/assets/6120860/27a165bf-c94c-4f16-82a0-0d0d8b0c6b77)

Idea version is 2023.3.1

com.intellij.util.IncorrectOperationException: Incorrect method '```Java
/**
 * Converts a byte array to a short array.
 *
 * @param bytes the input byte array.
 * @return the converted short array. If the input byte array is null, returns null.
 */
public  short[] bytesToShort(byte[] bytes) {
		if (bytes == null) {
			return null;
		}
		short[] shorts = new short[bytes.length / 2];
		ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(shorts);
		return shorts;
	}
```void m();'
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.newException(PsiJavaParserFacadeImpl.java:388)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:184)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createMethodFromText(PsiElementFactoryImpl.java:697)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:193)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createDocCommentFromText(PsiJavaParserFacadeImpl.java:123)

**Comment by phodal** [comment]
sometimes,  some LLM will return error format

**Comment by phodal** [comment]
已经修复。

临时版本可以从这里下载：https://github.com/unit-mesh/auto-dev/actions/runs/8181488068

新版本预计要下周发布

**Comment by lixikun** [comment]
> 已经修复。
> 
> 临时版本可以从这里下载：https://github.com/unit-mesh/auto-dev/actions/runs/8181488068 （在 Artifacts 区域）
> 
> 新版本预计要下周发布

高效，thanks!
